language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip -v install --allow-all-external --allow-unverified GnuPGInterface

#  - pip install --allow-all-external --allow-unverified GnuPGInterface -r partners_solution/requirements.txt
# command to run tests, e.g. python setup.py test
